### ISSUE TITLE
JTAC autolase est à côté de la cible

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#144]
Le JTAC lase à quelques mètres de la cible, du coup les tirs ratent.
Je pense que le souci vient de la méthode d'optimisation du lasing sur les cibles en mouvement (7b07f5a7ab73cd47a00e4cdb2c72c27c7944cb50 - enabled lase spot corrections).
Une solution serait d'estimer, en fonction de la vitesse de la cible au moment où la méthode `ctld.laseUnit` tourne, au bout de combien de temps il faut relancer le calcul du point de laser.
C'est peut-être même déjà fait, faut étudier ce que fait le code:
```lua
 --if the target is going sufficiently fast for it to wander off futher than the maxUpdateDist, schedule laseUnit calls to update the lase spot only (we consider that the unit lives and drives on between JTACAutoLase calls)
        if targetSpeed >= maxUpdateDist/refreshDelay then
            local updateTimeStep = maxUpdateDist/targetSpeed --calculate the time step so that the target is never more than maxUpdateDist from it's last lased position
            ctld.logDebug(string.format("updateTimeStep=%s", ctld.p(updateTimeStep)))

            local i = 1
            while i*updateTimeStep <= refreshDelay - updateTimeStep do --while the scheduled time for the laseUnit call isn't greater than the time between two JTACAutoLase() calls minus one time step (because at the next time step JTACAutoLase() should have been called and this in term also calls laseUnit())
                ctld.logTrace("ctld.laseUnit scheduled " .. i)
                timer.scheduleFunction(ctld.timerLaseUnit,{_enemyUnit, _jtacUnit, _jtacGroupName, _laserCode}, timer.getTime()+i*updateTimeStep)
                i = i + 1
            end
        end
```

**Comment by davidp57** [comment]
En cours de correction - il faudra encore tester l'implémentation suggérée (estimer, en fonction de la vitesse de la cible au moment où la méthode ctld.laseUnit tourne, au bout de combien de temps il faut relancer le calcul du point de laser)

**Comment by RexAttaque** [comment]
> Le JTAC lase à quelques mètres de la cible, du coup les tirs ratent. Je pense que le souci vient de la méthode d'optimisation du lasing sur les cibles en mouvement ([7b07f5a](https://github.com/VEAF/VEAF-Mission-Creation-Tools/commit/7b07f5a7ab73cd47a00e4cdb2c72c27c7944cb50) - enabled lase spot corrections). Une solution serait d'estimer, en fonction de la vitesse de la cible au moment où la méthode `ctld.laseUnit` tourne, au bout de combien de temps il faut relancer le calcul du point de laser. C'est peut-être même déjà fait, faut étudier ce que fait le code:
> 
> ```lua
>  --if the target is going sufficiently fast for it to wander off futher than the maxUpdateDist, schedule laseUnit calls to update the lase spot only (we consider that the unit lives and drives on between JTACAutoLase calls)
>         if targetSpeed >= maxUpdateDist/refreshDelay then
>             local updateTimeStep = maxUpdateDist/targetSpeed --calculate the time step so that the target is never more than maxUpdateDist from it's last lased position
>             ctld.logDebug(string.format("updateTimeStep=%s", ctld.p(updateTimeStep)))
> 
>             local i = 1
>             while i*updateTimeStep <= refreshDelay - updateTimeStep do --while the scheduled time for the laseUnit call isn't greater than the time between two JTACAutoLase() calls minus one time step (because at the next time step JTACAutoLase() should have been called and this in term also calls laseUnit())
>                 ctld.logTrace("ctld.laseUnit scheduled " .. i)
>                 timer.scheduleFunction(ctld.timerLaseUnit,{_enemyUnit, _jtacUnit, _jtacGroupName, _laserCode}, timer.getTime()+i*updateTimeStep)
>                 i = i + 1
>             end
>         end
> ```

Ce code planifie le rafraîchissement de la position du laser périodiquement en fonction de la vitesse de la cible si elle se déplace. Cela de sorte à ce que cette cible ne s'éloigne jamais d'une certaine distance du laser entre deux rafraîchissements.
Ce n'est pas la source du décallage observé cependant, au contraire cette boucle vise à le réduire pour les cibles en mouvement.

Dans le même commit qui a introduit le morceau de code que tu cites, deux décalages à la position du laser ont aussi été ajoutés pour aider les LGBs à frapper des cibles en mouvement "rapide" et/ou lorsqu'il y a de "forts" vents (on parle de 30km/h combiné, pas si énorme). L'amplitude de ces décalages dépend de la vitesse de la cible et du vent local et explique donc le phénomène que tu décris. Le code se situe dans la fonction ctld.laseUnit().
Il existe un paramètre pour les désactiver mais cela peut poser problème lorsqu'il s'agira de larguer des LGBs sur des blindés protégés par la grande muraille de vent même s'ils sont statiques.

**Comment by davidp57** [comment]
Ah ben j'ai peut-être pas compris le code alors ; je vais étudier ça de plus près.
Et ta remarque sur l'utilisation majoritaire vaut ce qu'elle vaut - mais moi je l'utilise 99% du temps avec des APKWS, et parfois en AH-64 ça peut être cool pour faire du toss au Hellfire.
Faudrait un moyen de choisir le comportement en vol, plutôt qu'à la compilation de la mission - oh, tiens, un menu radio JTAC avec une 9-line, tu te rappelles on en a parlé ? ;)
