### ISSUE TITLE
Bug commande QRA

### ISSUE THREAD

**Issue by veaf-Sharko** [VEAF/VEAF-Mission-Creation-Tools#154]
--if QRA_MINEVODY then QRA_MINEVODY:start() end
 --if QRA_MINEVODY then QRA_MINEVODY:stop() end

Je remarque un soucis avec ces commandes dans le sens stop > activation 

Lors d une mission je souhaite activer une QRA uniquement quand je le veux , je fais donc une trigger qui dis 
 une fois > Temps supp 3 sec > if QRA_MINEVODY then QRA_MINEVODY:stop() end 
 la qra est bien désactivée pas de soucis .
 
 Par contre au moment de la reactiver:
  une fois > si machin machin > if QRA_MINEVODY then QRA_MINEVODY:start() end
  Le message qui dis que QRA est online + le message qui dis que QRA est ready apparaissent normalement par contre la qra ne déploie pas d unité!
  
  Des lors qu il n y pas la commande if QRA_MINEVODY then QRA_MINEVODY:stop() end la qra fonctionne parfaitement
  
Je remarque que le message qra ready apparait avant le message qra online , est ce que ce serait pas ca qui crée le soucis

**Comment by davidp57** [comment]
closed in 5f86b8653933ec04df376d0c69ae2b5a49b55d4d
