### ISSUE TITLE
Amélioration des Zones de déclenchement

### ISSUE THREAD

**Issue by bourriquetFR** [VEAF/VEAF-Mission-Creation-Tools#172]
Bonjour,

Avec les outils VEAF, il est possible d'utiliser des zones de déclenchements pour des QRA.
Néanmoins, il serait intéressant que ces zones de déclenchement puissent l'être avec l'altitude.

**Comment by davidp57** [comment]
Réglé dans 2187a589afe5f5968ad35210fffd310253814de6
