### ISSUE TITLE
FARP en coalition neutre

### ISSUE THREAD

**Issue by tripack14** [VEAF/VEAF-Mission-Creation-Tools#191]
La génération par script ou par marqueur fait bien apparaitre la FARP, mais cette dernière est en NEUTRE.
Du coup pas moyen de rearm/refuel.

Seule la farp est neutre, les unités, tentes etc sont bien en bleu.
![2023-04-05_23h30_54](https://user-images.githubusercontent.com/106162778/230217010-b10ad047-5a7b-427e-a595-c475ae6288a3.png)

[Snowfox-VEAF_20230405.zip](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/11163308/Snowfox-VEAF_20230405.zip)

**Comment by tripack14** [comment]
![2023-04-05_23h31_04](https://user-images.githubusercontent.com/106162778/230217479-0c03f66f-c4fe-4444-830d-9c47bcfc23a3.png)

**Comment by davidp57** [comment]
Il semble que notre ami se soit fourvoyé... je cloture
