### ISSUE TITLE
CTLD - autolase ne fonctionne pas

### ISSUE THREAD

**Issue by tripack14** [VEAF/VEAF-Mission-Creation-Tools#205]
En déployant les troupes JTAC ou le Humvee JTAC près d'unités rouges, le message d'aquisition et de lasing s'affiche bien , mais ne fonctionne pas. (essai avec gbu, recherche via le pod)
![2023-04-12_01h00_59](https://user-images.githubusercontent.com/106162778/231371505-a0a51825-0e4c-485f-828d-910a1d945fc1.png)

**Comment by tripack14** [comment]
il y a ce message d'erreur dans le log
![2023-04-12_01h05_07](https://user-images.githubusercontent.com/106162778/231371646-b30f01f7-8d16-46dc-8dee-40feb4d88f0c.png)

**Comment by tripack14** [comment]
2023-04-11 22:23:20.680 ERROR   SCRIPTING (Main): Mission script error: [string "S:\Missions_edditing\Test-Snowfox-VEAF\node_modules\veaf-mission-creation-tools\/src/scripts/community/CTLD.lua"]:5618: attempt to index local '_enemyUnit' (a nil value)
stack traceback:
    [C]: ?
    [string "S:\Missions_edditing\Test-Snowfox-VEAF\node_modules\veaf-mission-creation-tools\/src/scripts/community/CTLD.lua"]:5618: in function 'createSmokeMarker'
    [string "S:\Missions_edditing\Test-Snowfox-VEAF\node_modules\veaf-mission-creation-tools\/src/scripts/community/CTLD.lua"]:5470: in function 'JTACAutoLase'
    [string "S:\Missions_edditing\Test-Snowfox-VEAF\node_modules\veaf-mission-creation-tools\/src/scripts/community/CTLD.lua"]:5540: in function <[string "S:\Missions_edditing\Test-Snowfox-VEAF\node_modules\veaf-mission-creation-tools\/src/scripts/community/CTLD.lua"]:5538>
2023-04-11 22:23:20.680 INFO    AV8B_CPT (Main): Ground Threats: Silkworm_SR (UK)

**Comment by tripack14** [comment]
[dcs.log](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/11207985/dcs.log)

**Comment by tripack14** [comment]
voici la mission épurée sur laquelle le bug est toujours présent
[test-VEAF_20230412.zip](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/11208003/test-VEAF_20230412.zip)

**Comment by tripack14** [comment]
J'ai testé en faisant spawner une unité JTAC via le marqueur de la carte F10, ça fonctionne parfaitement.

(D'ailleurs les fonctionnalités de choix de cibles etc via le JTAC spawner via maqueur VEAF seraient top si elle s'appliquaient aussi au JTAC généré par CTLD )

**Comment by RexAttaque** [comment]
https://github.com/ciribob/DCS-CTLD/issues/84
