### ISSUE TITLE
Fumigène et Flares inactif sur combazone 

### ISSUE THREAD

**Issue by tripack14** [VEAF/VEAF-Mission-Creation-Tools#213]
voici la mission:
les zone training sont:
Training Zone Khashuri
Training Zone Convoi Ruisi
Training Zone Building Gori

[training-BFR_20230416.zip](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/11241481/training-BFR_20230416.zip)

**Comment by davidp57** [comment]
corrigé dans la 5.23.2 avec plein d'autres trucs
