### ISSUE TITLE
veafSkynet never adds Point Defenses

### ISSUE THREAD

**Issue by MacFlorent** [VEAF/VEAF-Mission-Creation-Tools#227]
Issue opened for discussion.

A lots of code seems to be there to detect and assign point defenses automatically to nearby IADS sites, but it actually is never executed.

- `addGroupToNetwork` will only add a site as a point defense if asked to (that is if the parameter `pointDefense` is not nil)
- the only call to `addGroupToNetwork` (in `initializeIADS`) will pass this parameter based on the structure of the IADS, which is not yet built, so it is always empty (`false`)
- maybe it is possible for the caller to pre-build part of the structure to manually set point defenses but I don't understand how, and I'm not sure it is useful since in that case building the IADS manually entirely seems a better option

I began to work the issue as follows : 
- identifying potential point defenses base on an internal unit type list
- identifying assets that should not be defended (to avoid defending AAA, SA13, SA19, etc)
- asking `addGroupToNetwork` to try to add such sam sites as point defense for a nearby IADS site (this code was already there)

But it doesn't work well, because to find a site to defend, said site must have already been added to the network, which is not guaranteed.
I think doing this in two passes is the way to go.

**Comment by RexAttaque** [comment]
A point defense can be added when spawning dynamically via markers to the nearest SAM group or the specified group, the code is run and does work in that regard. What skynet actually does with point defenses, not really sure to be perfectly honnest. Requires testing.

Easiest way to fix the issue for mission makers is to add a delay when spawning point defenses and if the spawn area is unknown, specify the name of the group to defend to avoid being assigned to an Sa-15, Sa-19 etc. (AAA should not be part of the IADS and so should not be taken into account for point defences).

Now to fix this doing two passes is mandatory one way or the other, watchdog (if a group name is specified to defend) or a delayed addition as a point defense would work.

**Comment by MacFlorent** [comment]
An update: I'm currently working on this.

The idea is to have an *automatic* and *optional* point defence affectation to the elements of the network. Existing VEAF mechanics to find nearby units will be used for this.

### Rules of affectation
Point defences affectation will be done as follows, as per Skynet database types :
- only groups capable of engaging HARMs can be point defence
- "single" groups will be eligible to defend "complex" or "ewr" groups
- "complex" groups will be eligible to defend "ewr" groups
- "single" groups will never be defended

For example:
- A SA-15 should be eligible to defend a SA-2 or an SA-10
- A SA-10 should be eligible to defend an EWR, but *not* a SA-2 or another SA-10

### Additional information about the point defence mechanic in Skynet
Point defences are only used in conjunction with the HARM defence mechanic.
When an IADS detects and identifies a HARM, it will inform all of his sites of it. Each site will assess if it is at risk of being hit by said HARM (based on distance, aspect, speed). If it decides it is indeed at risk, it will : 
- Set all of his point defences to act as EW (that is, turn on or stay on).
- Check if itself or his point defences can intercept the threat (based on remaining ammo available) and if not, it will shutdown.

So in pratical terms, having point defences:
- Can allow a EWR to stay on when under HARM threat
- Can allow a SAM site to stay active when under HARM threat
- Ensures that point defences elements will not turn off to defend an inbound HARM and leave their protected element vulnerable to other interceptable munitions
