### ISSUE TITLE
Erreur coordonnées de Krasnodar Center sur le NAMED POINTS, List all points

### ISSUE THREAD

**Issue by tripack14** [VEAF/VEAF-Mission-Creation-Tools#228]
![image](https://github.com/VEAF/VEAF-Mission-Creation-Tools/assets/106162778/8803d391-d9ee-473d-a2d2-bebb757f8d55)

**Comment by davidp57** [comment]
Corrigé ! C'étaient les 2 seuls aéroports au nord de la ligne d'inversion de signe des coordonnées DCS et j'avais mis "-" au lieu de "+" !
J'en ai bavé pour trouver cette petite typo...
