### ISSUE TITLE
veafSkynet: option to add dynamically spawned groups to existing networks

### ISSUE THREAD

**Issue by MacFlorent** [VEAF/VEAF-Mission-Creation-Tools#235]
I'm opening this issue to notify that I am working on it, and to keep track on its existance and the progress on its resolution.
This would be an enhancement not an anomaly.

In its current form (as I understand it) veafSkynet is rather rigid and will only add units to iads networks:
- By a static and global initialization of the network, typically done at the start of the mission but also when a combatZone is deactivated
- By dynamically adding a group spawned by veafSpawn if required by the spawn command options

I think it used to be done when a combatZone was activated as well, but this was removed due to performance issues in big missions with big iads networks.

It would be better if veafSkynet was capable of integrating dynamically spawned units in existing networks, regardless of the method by which they are spawned. Obviously.
Real cases were identified by @veaf-Sharko and include:
- AWACS spawned as QRA
- SAM sites distant from the action, spawned as required only to lighten mission footprint

To do this we will have to monitor the unit birth event and act on it accordingly. When a group is spawned it should be checked for eligibility, and if eligible for skeynet, be added to the network of its coalition.
This should be done:
- At a group granularity, not by reinitializing the whole network
- With particular care to performance, as we don't want to have a lot of stuff done each time a unit is spawned
- Optionaly, so only when explicitly required by the mission maker

To be further analysed:
An eligible group will be a group that is supported by skynet, but some additional constraints may have to be added, such as is the group moving (convoys). But this may also be a thing to check for static initialization of the network ?

**Comment by davidp57** [comment]
Good points, clear explanation.
Regarding the monitoring of birth events, we could use the new veafEventHandler module.

**Comment by MacFlorent** [comment]
Sorry I did not use veafEventHandler but maybe for another iteration. If you want to have a look ping me over Discord.
