### ISSUE TITLE
Modifier CTLD pour trigger.action.radioTransmission

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#238]
Il semble que cette méthode ne fonctionne plus si on ne met pas de nom (symptome: 1 sec de transmission et puis stop).
[Source](https://forum.dcs.world/topic/316378-placed-adf-beacons-only-transmit-briefly/)

De plus, il paraît que ce n'est plus la peine de rescheduler toutes les 30 secondes, l'option "loop" refonctionne en multi.
[Source](https://forum.dcs.world/topic/276106-arc-frequencies/page/2/)

A tester, + PR pour Ciribob dans CTLD et dans CSAR (faire tester par Tripack)

**Comment by tripack14** [comment]
je confirme que l'ADF d'une farp qui spwan via la map F10 n'émet que durant 2 secondes avec un espacement de 30 seconde

**Comment by davidp57** [comment]
Fait, y'a plus qu'à faire un PR à Ciribob
