### ISSUE TITLE
soucis de pathfinding des convois

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#255]
essayer d'utiliser getClosestPointOnRoads  pour envoyer d'abord le convoi vers une route (1er point)

**Comment by RexAttaque** [comment]
c'est déjà ce qui est fait

**Comment by davidp57** [comment]
[Effectivement](https://github.com/VEAF/VEAF-Mission-Creation-Tools/commit/2212bcc8e0ea103aae710882361903bc22e4a8c7); dommage ça paraissait prometteur.
Merci de m'avoir signalé ça !
