### ISSUE TITLE
CSAR - problème avec FARP invisible

### ISSUE THREAD

**Issue by tripack14** [VEAF/VEAF-Mission-Creation-Tools#258]
Une fois le pilote à bord et qu'on le ramène sur une FARP invisible, celui-ci n'est pas déchargé.

Sur une FARP "normale" cela fonctionne bien

log en annexe au moment où l'on pose sur la FARP invisible
[dcs.log](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/14232926/dcs.log)
![DCS 2024-02-11 16-44-01 original](https://github.com/VEAF/VEAF-Mission-Creation-Tools/assets/106162778/8e17cf82-6b81-4bd9-bff6-64bb084d06b1)

**Comment by davidp57** [comment]
[Reporté](https://github.com/ciribob/DCS-CSAR/issues/13) sur le GitHub de CSAR.
Je cloture ici.
