### ISSUE TITLE
erreur de coordonnées dans la commande /alias en UTM

### ISSUE THREAD

**Issue by mitch10593** [VEAF/VEAF-Mission-Creation-Tools#46]
Commande lancée:

```
/alias U37SBT5442105271 -infantry, side red, defense 0, armor 0
```

Résultat / attendu:
![image](https://user-images.githubusercontent.com/10455897/115432479-b24fa680-a206-11eb-9a7f-edf07a62c501.png)

Bug probable: le "0" en tête de la coordonnée Y est ignoré, le spawn ayant eu lieu vers U37SBT 54 52 au lieu de U37SBT 54 05

**Comment by davidp57** [comment]
Corrigé dans 9e8eb9b938f476db55cd62027d724de9e378508e

![image](https://user-images.githubusercontent.com/172286/115552127-3740cb80-a2ac-11eb-9e81-0e3a9f497b7f.png)
