### ISSUE TITLE
Ajouter des vagues d'ennemis au script trainingSpawnZone

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#51]
Le but est que la zone de training soit capable de spawn des vagues de groupes ennemis, un groupe après l'autre, à la destruction du précédent, jusqu'à la fin de la liste.

Un truc du genre 
```lua
trainingSpawnZone.registerZone("BVR 1", {"BVR Stage² 1vs1 Su33"}, {"Su 33 1vs1 step 1", "Su 33 1vs1 step 2", "Su 33 1vs1 step 3", "Su 33 1vs1 step 4"}, 30, true)
```
Où tous les "Su 33 1vs1 step x" sont des groupes format les vagues (on peut remettre plusieurs fois le même groupe, il sera respawn) et le "30" le délai entre la destruction d'une vague et le lancement d'une autre.

**Comment by veaf-Sharko** [comment]
Si possible afficher un message du style premiere vague detruite 2 eme blabla et comble du comble si a la fin je peu genre jouer un morceau .ogg la cerise sur le gateau Merci a toi as always

**Comment by davidp57** [comment]
https://veaf.github.io/documentation/mission-maker/airwaves.html
