### ISSUE TITLE
CTLD : a way to "Pass or Skip" on a lased target

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#58]
As asked [here](https://forums.eagle.ru/topic/120045-complete-transport-and-logistics-deployment-ctld/page/42/?tab=comments#comment-4679628). 
This would actually be great, using a radio command and a SRS radio message for confirmation.

**Comment by RexAttaque** [comment]
Possible with the changes in pull request #99, feature is experimental and requires extensive testing

**Comment by RexAttaque** [comment]
Added in CTLD
