### ISSUE TITLE
On pourrait solutionner le pb des unités au sol qui s'arrêtent en changeant leur vitesse régulièrement

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#61]
https://forums.eagle.ru/topic/268915-path-finding-broken-27-track-attached/page/2/?tab=comments#comment-4687031

**Comment by RexAttaque** [comment]
Cela fonctionne lorsque toutes les unités du groupe s'arrêtent puis reprennent la route mais ne solutionne pas le problème de pathfinding sous jacent qui est que dans certaines conditions (si une tâche GoToWaypoint est utilisée, si le groupe est mal pacé au spawn etc.) et bien le curseur du pathfinding se barre très loin devant le groupe puisqu'il ne prend plus en compte la vitesse réelle du groupe (ce que vous pouvez voir en cliquant sur une unité du groupe puis en regardant le début de la route en pointillets jaunes). 

Arrêter puis redémarrer le groupe remet le curseur sur la première unité mais peu de temps après il faut recommencer la manipe.

Pour solutionner les problèmes que en tout cas nous avons, il semblerait que, faire spawner puis disparaître une unité dans un groupe au départ empêche l'IA de se mettre dans un mode pathfinding bizarre (plus flexible etc.) qui fait qu'ils sortent de la route, se coincent et bloquent les autres au passage. Le problème du curseur de pathfinding qui part loin devant le groupe intervient aussi après les premiers blocages.
Deuxièmement, pour les patrouilles, au lieu d'utiliser GoToWaypoint, on affecte de nouveau au convoi sa route qui constitue un aller et un retour au point de départ, à chaque fois qu'il passe par le point de départ.
