### ISSUE TITLE
https://wiki.hoggitworld.com/view/DCS_option_disperseOnAttack

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#79]

**Comment by RexAttaque** [comment]
L'option disperse a été rajoutée, la valeur spécifiée en seconde défini le temps de dispersion, à tester si ça apporte quelque chose.

**Comment by RexAttaque** [comment]
C'est très bien comme option, à 15secondes pour les convoys ça rend les mouvements pas mal plus chaotiques
