### ISSUE TITLE
rajouter une option pour spawner un convoi plus resserré

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#84]
De Skull : "Rien que le temps que le convoi se mette en route ça a pri quasi 20 min. La dispersion des véhicules autour de la route a fait perdre du temps."

**Comment by RexAttaque** [comment]
Une solution pour "accélérer", mettre les unités en file indienne dans le groupe convoy dans la direction de la route (à l'utilisateur de définir ce heading malheureusement). Potentiellement limiter la taille des convoys et faire des clusters. 

On ne pourra pas fixer le pathfinding de DCS qui faire partir les unités une par une sur la route j'ai bien peur.

Je teste la première solution, ça paraît très bien fonctionner.

**Comment by RexAttaque** [comment]
Solution de faire spawner les convois en file indienne implémentée, avec de plus l'option heading ajoutée là où il fallait pour faire spawner les colonnes le long de la route, a tester mais de mon côté ça paraissait efficace.

**Comment by RexAttaque** [comment]
Les unités de la colonne ont maintenant le même heading pour vraiment faire une file indienne
