### ISSUE TITLE
IADS : ajouter une option pour actAsEwr

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#85]
Pour pouvoir modifier la liste des SAM qui act comme EWR

**Comment by The-Skull** [comment]
Tu veux :
- ajouter une option à parser dans veafSpawn.markTextAnalysis
- pour que dans veafSkynet.addGroupToNetwork appelé par veafSpawn.executeCommand
- on ait (ou pas) setActAsEW(true) qui soit exécuté ?

**Comment by RexAttaque** [comment]
J'ai rajouté l'option forceEwr qui pour le coup force une unité en tant qu'EWR, ça peut s'étendre facilement pour faire l'inverse y'a-t-il un intérêt ?

**Comment by veaf-Sharko** [comment]
normalement non avec les mises a jour tout y a plus de probleme

**Comment by davidp57** [comment]
Du coup je cloture cette demande; merci !
