### ISSUE TITLE
Tacan Bleu lors de la generation d une farp Red

### ISSUE THREAD

**Issue by veaf-Sharko** [VEAF/VEAF-Mission-Creation-Tools#89]
lors de la creation d une farp rouge via le script , au moment de la generation du groupe au lancement de la mission, apparait un tacan bleu et lieu et place d un tacan rouge, ce qui fait que les unités au sol du secteur lui tire dessus et le detruise.

**Comment by veaf-Sharko** [comment]
Faire en sorte si possible que les unites generes pour la creation de la farp soit toutes invisible

**Comment by RexAttaque** [comment]
la coalition et le pays du FARP n'étaient pas pris en compte lors du spawn du tacan, réglé

veafGrass.lua - ligne 417
