### ISSUE TITLE
Bug carrier operation

### ISSUE THREAD

**Issue by veaf-Sharko** [VEAF/VEAF-Mission-Creation-Tools#92]
Lorsqu on lance le carrier operation la premiere fois, tout se passe bien par contre ensuite dans le menu radio, ca apparait en doublon et ca semble etre bloqué 
![image](https://user-images.githubusercontent.com/83705611/171628656-33e5a2d6-5e36-48bd-988b-1d0593bf6f6c.png)

**Comment by RexAttaque** [comment]
L'erreur venait du fait que les mauvais sous-menus radios étaient supprimés. Pour être exact, le menu de chaque carrier était supprimé et non pas le contenu de chaque menu et du coup la suppression côté DCS échouait en partie (en tout cas les commandes derrières les menus disparaissaient mais pas les intitulés dans le menu radio). Puis après on essayait de rajouter les menus qui n'avaient jamais disparus donc ça faisait n'importe quoi.

veafCarrierOperations.lua - commande ligne 772
