### ISSUE TITLE
/Point atc visible uniquement groupe voir unité

### ISSUE THREAD

**Issue by veaf-Sharko** [VEAF/VEAF-Mission-Creation-Tools#93]
est il possible de faire en sorte que lorsqu on fait weather on closest point ou /point atc , le message produit n appairaissent que au groupe ou alors a l unité directement (suite a la maj qui le permet)

Objectif ne pas polluer de message si y a 30 personnes sur un serveur et 5 qui s en servent a tour de role

**Comment by RexAttaque** [comment]
Normalement c'est fait, à tester
