### ISSUE TITLE
Ajout HQ-7 a IADS

### ISSUE THREAD

**Issue by veaf-Sharko** [VEAF/VEAF-Mission-Creation-Tools#94]
ne plus mettre les H-7Q en Ewr

        iads:getSAMSitesByNatoName('CSA-4'):setActAsEW(false)
![image](https://user-images.githubusercontent.com/83705611/171930048-0a6e1383-ee6b-4bce-ab2b-fbee3c83c733.png)

**Comment by RexAttaque** [comment]
ça a été réglé côté IADS non ? Pour moi le STR se comporte comme un STR et non pas comme un EWR actuellement.

**Comment by veaf-Sharko** [comment]
effectivement , je suis retourne check, soit c etait une erreur de ma part a l epoque, soit ca a changé dans iads direct (ce dont je doute), en tous cas la ligne n as pas été ajoutée au scripts donc a voir mais il n agit pas en EWR actuellement

**Comment by RexAttaque** [comment]
à priori plus un problème
